---
- name: restart forgejo
  ansible.builtin.systemd_service:
    name: forgejo
    state: restarted
    scope: user
    daemon_reload: true
  become: true
  become_user: "{{ podman_forgejo_podman_rootless_user }}"

- name: restart mariadb
  ansible.builtin.systemd_service:
    name: forgejo
    state: restarted
    scope: user
    daemon_reload: true
  become: true
  become_user: "{{ podman_forgejo_podman_rootless_user }}"

- name: restart sshd
  service:
    name: sshd
    state: restarted
  become: true
