---
- name: restart certbot-renew
  ansible.builtin.systemd_service:
    name: certbot-renew
    state: started
    scope: user
    daemon_reload: true
  become: true
  become_user: "{{ podman_nginx_podman_rootless_user }}"

- name: restart nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
    scope: user
    daemon_reload: true
  become: true
  become_user: "{{ podman_nginx_podman_rootless_user }}"
